### ISSUE TITLE
is this working project?

### ISSUE THREAD

**Issue by gandhrekunal** [tmheo/spring-data-jpa-redshift-sample#1]
Hey I am looking for some sort same solution 

is this working project?

**Comment by tmheo** [comment]
Hello, @gandhrekunal 

Yes, this worked when I tested.

**Comment by gandhrekunal** [comment]
Hey, @tmheo thanks.

How to test the code, it did not have any web service/ junit. Please update me if i am wrong

**Comment by gandhrekunal** [comment]
hey @tmheo  it worked, I tried using jersey rest + JAP + Hibernate. 👍
